neighbors:
  metric: 'topological'                      # ['topological', 'eucledian', 'voronoi', 'vlos']
  count: 3                            # For topological: how many neighbors
  range: 0.5                          # Sensing range (radius) of the drone
  r_agent: 0.069                      # Radius of an agent (for vlos neighbor metric)

viewing:
  metric: 'convex_hull'                # ['average', 'tangent_plane', 'convex_hull']
  faces: 'adjacent'                   # For convex hull algo only: ['adjacent', 'visible']